In [2]:
import os
import cv2
import argparse
import numpy as np

frame_name = "in" + str(1).zfill(6) + ".jpg"
frame = cv2.imread("baseline/input/" + frame_name)

In [7]:
import subsense

BASELINE_FRAMES = 1700
ILLUMINATION_FRAMES = 301
JITTER_FRAMES = 1150
DYNAMIC_FRAMES = 1189
PTZ_FRAMES = 1130

backSub = cv2.createBackgroundSubtractorMOG2(varThreshold=30, detectShadows=False)
kernel = np.ones((5,5),np.uint8)

for i in range(1, BASELINE_FRAMES+1):
    frame_name = "in" + str(i).zfill(6) + ".jpg"
    frame = cv2.imread("baseline/input/" + frame_name)
    subsense.compute_lbsp(frame, 0.3)
    keyboard = cv2.waitKey(30)
    if keyboard == 'q' or keyboard == 27:
        break

Process ForkPoolWorker-22:
Process ForkPoolWorker-13:
Process ForkPoolWorker-7:
Process ForkPoolWorker-2:
Process ForkPoolWorker-4:
Process ForkPoolWorker-23:
Process ForkPoolWorker-18:
Process ForkPoolWorker-19:
Process ForkPoolWorker-17:
Process ForkPoolWorker-1:
Process ForkPoolWorker-15:
Process ForkPoolWorker-12:
Process ForkPoolWorker-9:
Process ForkPoolWorker-6:
Process ForkPoolWorker-14:
Process ForkPoolWorker-5:
Process ForkPoolWorker-3:
Process ForkPoolWorker-20:
Process ForkPoolWorker-11:
Process ForkPoolWorker-21:
Process ForkPoolWorker-8:
Process ForkPoolWorker-10:
Process ForkPoolWorker-16:
Process ForkPoolWorker-24:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (

  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/Users/shreyansnagori/op

  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
  File "/Users/shreyansnag

KeyboardInterrupt: 

Process ForkPoolWorker-26:
Process ForkPoolWorker-32:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/shreyansnagori/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/shreyansnagori/opt/an

In [32]:
import random 
import subsense

class Subsense_background:
    def __init__(self,shape,d_init,v_init,r_init,t_init,r_color_0,r_lbsp_0,n_min,learn_rate):
        self.h, self.w, self.c = shape
        self.background_model = []
        self.prev_map = np.full((self.h,self.w),0)
        for i in range(0,50):
            x1 = random.randint(0,self.h-1)
            y1 = random.randint(0,self.w-1)
            self.background_model.append((x1,y1))
        
        self.d_min = np.full((self.h,self.w),d_init)
        self.v = np.full((self.h,self.w),v_init)
        self.r = np.full((self.h,self.w),r_init)
        self.t = np.full((self.h,self.w),t_init)
        self.r_color_0 = r_color_0
        self.r_lbsp_0 = r_lbsp_0
        self.n_min = n_min
        self.learn_rate = learn_rate
        
    def apply(self, img):
        r_color = self.r * self.r_color_0
        r_lbsp = np.power( np.full((self.h,self.w),2), self.r) + self.r_lbsp_0
        self.curr_segmentation = np.full((self.h,self.w),1)
        self.lbsp,self.intensity = subsense.compute_lbsp(img, 0.3)
        self.distance_tot = np.full((self.h,self.w),0)
        
        for i in range(0,self.h):
            for j in range(0,self.w):
                pixel_lbsp = self.lbsp[i,j]
                pixel_intensity = self.intensity[i,j]
                no_matches = 0
                sum_store = 0
                for k in range(0,len(self.background_model)):
                    temp_pixel_lbsp = self.lbsp[self.background_model[k][0],self.background_model[k][1]]
                    temp_pixel_intensity = self.intensity[self.background_model[k][0],self.background_model[k][1]]
                    dist_lbsp = subsense.hamming_distance(pixel_lbsp,temp_pixel_lbsp)
                    dist_intensity = abs(temp_pixel_intensity - pixel_intensity)
                    sum_store = sum_store + dist_lbsp
                    sum_store = sum_store + dist_intensity
                    if dist_lbsp > r_lbsp[i,j]:
                        continue
                    if dist_intensity > r_color[i,j]:
                        continue
                    no_matches = no_matches + 1
                self.distance_tot[i,j] = sum_store
                if no_matches >= self.n_min:
                    self.curr_segmentation[i,j] = 0
                store = random.uniform(0, 1)
                if store <= self.t[i,j]:
                    idx = random.randint(0,len(self.background_model)-1)
                    self.background_model[idx] = (i,j)
                
                
        #Now for updates
        mean = np.mean(self.distance_tot.flatten())
        variance = np.std(self.distance_tot.flatten())
        self.distance_tot = (self.distance_tot - mean)/ variance
        self.d_min = (1- self.learn_rate)* self.d_min + self.learn_rate * self.distance_tot
        
        self.xor_store = self.curr_segmentation ^ self.prev_map
        self.prev_map = self.curr_segmentation
        
        for i in range(0,self.h):
            for j in range(0,self.w):
                if self.xor_store[i,j] == 1 :
                    self.v[i,j] = self.v[i,j] + 1
                else:
                    self.v[i,j] = self.v[i,j] - 0.1

        
        for i in range(0,self.h):
            for j in range(0,self.w):
                if self.r[i,j] >= (1 + self.d_min[i,j]*2) ** 2 :
                    self.r[i,j] = self.r[i,j] + self.v[i,j]
                else:
                    self.r[i,j] = self.r[i,j] - (1/self.v[i,j])
                    
        for i in range(0,self.h):
            for j in range(0,self.w):
                if self.curr_segmentation[i,j] == 1:
                    self.t[i,j] = self.t[i,j] + 1/(self.v[i,j]*self.d_min[i,j])
                else:
                    self.t[i,j] = self.t[i,j] - (self.v[i,j]/self.d_min[i,j])
        return self.curr_segmentation
        
        

        

In [2]:
Subsense_background_model = subsense.Subsense(0.5, 0, 1, 5, 2, 0.1)
frame_name_2 = "in" + str(2).zfill(6) + ".jpg"
frame2 = cv2.imread("COL780-A1-Data/baseline/input/" + frame_name_2)
mask = Subsense_background_model.apply(frame2)
print(mask)


[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


/home/s7rthak/Sem-7/Computer-Vision-A1/subsense.py:177: RuntimeWarning: invalid value encountered in true_divide
  self.distance_tot = (self.distance_tot - mean)/ variance


In [4]:
import os
import cv2
import argparse
import numpy as np
import subsense

BASELINE_FRAMES = 1700

backSub3 = subsense.Subsense(0.5, 0.1, 1, 2, 2, 0.1)

for i in range(1, BASELINE_FRAMES+1):
    print(i)
    frame_name = "in" + str(i).zfill(6) + ".jpg"
    frame = cv2.imread("COL780-A1-Data/baseline/input/" + frame_name)

    print(backSub3.t)

    # gaussian = cv2.GaussianBlur(frame,(3,3),0)
    # fgMask = backSub2.apply(gaussian)
    # closing = cv2.morphologyEx(fgMask, cv2.MORPH_CLOSE, kernel)
    # opening = cv2.morphologyEx(closing, cv2.MORPH_OPEN, kernel)
    # res = cv2.GaussianBlur(opening,(3,3),0)
    # opening2 = cv2.morphologyEx(res, cv2.MORPH_OPEN, kernel)
    # closing2 = cv2.morphologyEx(opening2, cv2.MORPH_CLOSE, kernel)

    if i >= 10:
        pred_name = "gt" + str(i).zfill(6) + ".png"
        cv2.imwrite("COL780-A1-Data/baseline/result/" + pred_name, backSub3.apply(frame))
    else:
        backSub3.apply(frame)

1
None
2
[[-9223372036854775808 -9223372036854775808 -9223372036854775808 ...
  -9223372036854775808 -9223372036854775808 -9223372036854775808]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808 ...
  -9223372036854775808 -9223372036854775808 -9223372036854775808]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808 ...
  -9223372036854775808 -9223372036854775808 -9223372036854775808]
 ...
 [-9223372036854775808 -9223372036854775808 -9223372036854775808 ...
  -9223372036854775808 -9223372036854775808 -9223372036854775808]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808 ...
  -9223372036854775808 -9223372036854775808 -9223372036854775808]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808 ...
  -9223372036854775808 -9223372036854775808 -9223372036854775808]]


/home/s7rthak/Sem-7/Computer-Vision-A1/subsense.py:177: RuntimeWarning: invalid value encountered in true_divide
  self.distance_tot = (self.distance_tot - mean)/ variance


ValueError: p < 0, p > 1 or p contains NaNs